---
- name: Create scan wrapper script
  template:
    src: scan-wrapper.sh.j2
    dest: "{{ safetyscan_bin_dir }}/safetyscan-wrapper-{{ item.name }}.sh"
    mode: '0755'
  loop: "{{ safetyscan_projects }}"
  when:
  - item.schedule is defined
  - item.enabled | default(true)

- name: Configure cron jobs for scheduled scans
  cron:
    name: "SafetyScan - {{ item.name }}"
    minute: "{{ item.schedule.split()[0] }}"
    hour: "{{ item.schedule.split()[1] }}"
    day: "{{ item.schedule.split()[2] }}"
    month: "{{ item.schedule.split()[3] }}"
    weekday: "{{ item.schedule.split()[4] }}"
    job: "{{ safetyscan_bin_dir }}/safetyscan-wrapper-{{ item.name }}.sh >> {{ safetyscan_log_file }} 2>&1"
    user: root
    state: present
  loop: "{{ safetyscan_projects }}"
  when:
  - item.schedule is defined
  - item.enabled | default(true)

- name: Remove cron jobs for disabled projects
  cron:
    name: "SafetyScan - {{ item.name }}"
    state: absent
  loop: "{{ safetyscan_projects }}"
  when:
  - item.schedule is defined
  - not (item.enabled | default(true))
